// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	models "avito-test/internal/models"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AuthentificationService is an autogenerated mock type for the AuthentificationService type
type AuthentificationService struct {
	mock.Mock
}

// CheckAuthorization provides a mock function with given fields: _a0, _a1
func (_m *AuthentificationService) CheckAuthorization(_a0 context.Context, _a1 []byte) (models.EnumRole, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CheckAuthorization")
	}

	var r0 models.EnumRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) (models.EnumRole, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte) models.EnumRole); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.EnumRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DummyAuthorize provides a mock function with given fields: _a0, _a1
func (_m *AuthentificationService) DummyAuthorize(_a0 context.Context, _a1 models.EnumRole) (string, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DummyAuthorize")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.EnumRole) (string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.EnumRole) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.EnumRole) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthentificationService creates a new instance of AuthentificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthentificationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthentificationService {
	mock := &AuthentificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
