// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EnumRole is an autogenerated mock type for the EnumRole type
type EnumRole struct {
	mock.Mock
}

// isEnumRole provides a mock function with given fields:
func (_m *EnumRole) isEnumRole() {
	_m.Called()
}

// NewEnumRole creates a new instance of EnumRole. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEnumRole(t interface {
	mock.TestingT
	Cleanup(func())
}) *EnumRole {
	mock := &EnumRole{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
