// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ModerationStatus is an autogenerated mock type for the ModerationStatus type
type ModerationStatus struct {
	mock.Mock
}

// String provides a mock function with given fields:
func (_m *ModerationStatus) String() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// isEnumStatus provides a mock function with given fields:
func (_m *ModerationStatus) isEnumStatus() {
	_m.Called()
}

// NewModerationStatus creates a new instance of ModerationStatus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModerationStatus(t interface {
	mock.TestingT
	Cleanup(func())
}) *ModerationStatus {
	mock := &ModerationStatus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
