services:
  house_db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_DB=${HOUSE_DB}
      - POSTGRES_USER=${HOUSE-DB_USER}
      - POSTGRES_PASSWORD=${HOUSE-DB_PASSWORD}
    volumes:
      - ../sql:/docker-entrypoint-initdb.d
  user_db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_DB=${HOUSE_DB}
      - POSTGRES_USER=${HOUSE-DB_USER}
      - POSTGRES_PASSWORD=${HOUSE-DB_PASSWORD}
  server:
    environment:
      - HOUSE_DB=${HOUSE_DB}
      - HOUSE-DB_USER=${HOUSE-DB_USER}
      - HOUSE-DB_PASSWORD=${HOUSE-DB_PASSWORD}
      - USER-DB=${HOUSE_DB}
      - USER-DB_USER=${HOUSE-DB_USER}
      - USER-DB_PASSWORD=${HOUSE-DB_PASSWORD}
    build:
      context:    ../
      dockerfile: ./deploy/Dockerfile
    restart: always

    ports:
      - "8000:8000"